### ISSUE TITLE
math-random dependency was not found when using @1.0.3

### ISSUE THREAD

**Issue by carautenbach** [michaelrhodes/math-random#4]
When building my project with 1.0.3 I get the following error:

This dependency was not found:
`* math-random in ./node_modules/randomatic/index.js`

@1.0.2 works.

**Comment by spapaseit** [comment]
@carautenbach How do you force Randomatic to use @1.0.2?

**Comment by carautenbach** [comment]
I install math-random separately using `npm install math-random@1.0.2 --save`

**Comment by spapaseit** [comment]
But of course. Thanks man.

**Comment by carautenbach** [comment]
Pleasure

**Comment by michaelrhodes** [comment]
Hi there, I’m having trouble recreating this issue. I was able to `npm install randomatic` and run a script whose source was `console.log(require('randomatic')('*', 10))`. I was also able to clone the `randomatic` repo, install its dependencies, and successfully run its tests.

Can you please point me in the right direction?

**Comment by carautenbach** [comment]
Hey. I'll try my best:
1. I'm running it on node:7
2. I'm using `https://www.npmjs.com/package/vue-tables-2` which is dependent on randomatic which uses math-random
3. If you can't replicate it we can close this, it is just good reference for anyone that is running into the same problem.
4. @spapaseit maybe you can explain how you got the error? 

Thanks

**Comment by spapaseit** [comment]
Well, I didn't even know I was using `randomatic` (and hence `math-random`). It's a dependency of a dependency of... in quite a large [Aurelia](https://aurelia.io) + Webpack setup.

I'll dig deeper.

**Comment by michaelrhodes** [comment]
Thanks for the info, gang. I’m currently suspecting something messed up your `node_modules` directories. I had a dependency magically disappear from a project today, so maybe an npm issue… _who knows?!_

I’ll leave this issue open for now. I’d be interested to know if a “quick” `rm -rf ./node_modules && npm install` resolves it

**Comment by carautenbach** [comment]
It is running on a runner from scratch every time, so in my instance it can't be a node_modules issue. Good luck.

**Comment by pward123** [comment]
fyi, I get the same error trying to use randomatic which depends on this library. In my case, it's webpack that is complaining.

This is happening in our CI servers which currently build in a new docker container each time and don't use an npm/yarn cache.

**Comment by pward123** [comment]
I've created a minimum reproduction here https://github.com/pward123/math-random-webpack-issue

**Comment by spapaseit** [comment]
> This is happening in our CI servers which currently build in a new docker container each time and don't use an npm/yarn cache.

same for me, by the way

**Comment by michaelrhodes** [comment]
Great work, @pward123! That got me to the problem pretty quickly: seems `webpack` has trouble parsing the browser field of `package.json` files. In any event, I have shuffled some things around and published 1.0.4 which should resolve the issue!

**Comment by spapaseit** [comment]
Tested, the fix works. Thanks @michaelrhodes, I think you can close this bug.
